backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Koreanische Speisen"
    name: "koreanische speisen"
    editor:
      preview: false
    files:
      - label: "Speisekarte"
        name: "speisekarte"
        file: "src/_data/korean.json"
        fields:
          - label: 식사류
            name: 식사류
            widget: list
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Preis, name: price, widget: string }
          - label: 면류 
            name: 면류
            widget: list
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Preis, name: price, widget: string }
          - label: 탕류 
            name: 탕류
            widget: list
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Preis, name: price, widget: string }
          - label: 안주류 
            name: 안주류
            widget: list
            fields:
              - { label: Name, name: title, widget: string }
              - { label: Preis, name: price, widget: string }
              - { label: Text, name: text, widget: string, required: false }
  - label: "Deutsche Speisen"
    name: "deutsche speisen"
    editor:
      preview: false
    files:
      - label: "Speisekarte"
        name: "speisekarte"
        file: "src/_data/german.json"
        fields:
          - label: koreanische Spezialität
            name: korSpez
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Scharf, name: scharf, widget: boolean, default: true }
              - { label: Name, name: title, widget: string }
              - { label: Beschreibung, name: desc, widget: string }
              - { label: Allergene, name: allergene, widget: string, required: false }
              - { label: Preis, name: price, widget: string }
          - label: Nudelgericht
            name: nudelgericht
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Scharf, name: scharf, widget: boolean, default: true }
              - { label: Doppelscharf, name: doppeltScharf, widget: boolean, default: false }
              - { label: Name, name: title, widget: string }
              - { label: Beschreibung, name: desc, widget: string }
              - { label: Allergene, name: allergene, widget: string, required: false }
              - { label: Preis, name: price, widget: string }
          - label: Reisgericht
            name: reisgericht
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Scharf, name: scharf, widget: boolean, default: true }
              - { label: Name, name: title, widget: string }
              - { label: Beschreibung, name: desc, widget: string }
              - { label: Allergene, name: allergene, widget: string, required: false }
              - { label: Preis, name: price, widget: string }
          - label: Suppengericht
            name: suppengericht
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Scharf, name: scharf, widget: boolean, default: true }
              - { label: Name, name: title, widget: string }
              - { label: Beschreibung, name: desc, widget: string }
              - { label: Allergene, name: allergene, widget: string, required: false }
              - { label: Preis, name: price, widget: string }
  - label: "BBQ koreanisch"
    name: "bbq koreanisch"
    editor:
      preview: false
    files:
      - label: "BBQ"
        name: "bbq"
        file: "src/_data/bbqKr.json"
        fields:
          - label: Menu
            name: menu
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Name, name: title, widget: string }
              - { label: Erwachsener, name: adult, widget: string, default: "성인"}
              - { label: Preis Erwachsener, name: preis_adult, widget: string }
              - { label: Kind, name: kid, widget: string, default: "어린이 (5-9)"}
              - { label: Preis Kind, name: preis_kid, widget: string }
              - { label: Einzel, name: einzel, widget: string, default: "단품 (160g)" }
              - { label: Preis Einzel, name: preis_einzel, widget: string }
              - { label: Beschreibung, name: desc, widget: string }
  - label: "BBQ deutssch"
    name: "bbq deutssch"
    editor:
      preview: false
    files:
      - label: "BBQ"
        name: "bbq"
        file: "src/_data/bbqGer.json"
        fields:
          - label: Menu
            name: menu
            widget: list
            fields:
              - { label: ID, name: id, widget: string }
              - { label: Name, name: title, widget: string }
              - { label: Erwachsener, name: adult, widget: string, default: "Erwachsene"}
              - { label: Preis Erwachsener, name: preis_adult, widget: string }
              - { label: Kind, name: kid, widget: string, default: "Kind (5-9)"}
              - { label: Preis Kind, name: preis_kid, widget: string }
              - { label: Einzel, name: einzel, widget: string, default: "Einzelpreis pro 160g" }
              - { label: Preis Einzel, name: preis_einzel, widget: string }
              - { label: Beschreibung, name: desc, widget: string }
          
  