backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Koreanische Speisen"
    name: "koreanische speisen"
    editor:
      preview: false
    files:
      - label: "Speisekarte"
        name: "speisekarte"
        file: "src/_data/korean.json"
        fields:
          - label: 식사류
            name: sigsalyu
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Preis, name: preis, widget: string }
          - label: 면류 
            name: myeonlyu
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Preis, name: preis, widget: string }
          - label: 탕류 
            name: tanglyu
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Preis, name: preis, widget: string }
          - label: 안주류 
            name: anjulyu
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Preis, name: preis, widget: string }
              - { label: Text, name: text, widget: string, required: false }
        